version: "3.0"

services:
  django:
    env_file: ./django/.env.webapp.prod
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8000
    image: ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/django_webapp:latest
    # volumes:
    #   - media_volume:/home/app/web/media

  nginx:
    build: ./nginx
    image: ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/django_nginx:latest
    # volumes:
    #   - media_volume:/home/app/web/media

# volumes:
#   media_volume:
