version: "3.0"

services:
  django:
    build: ./django
    env_file: ./django/.env.webapp
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    networks:
      - django-network

  nginx:
    build: ./nginx/local
    restart: always
    ports:
      - 443:443
    depends_on:
      - django
    networks:
      - django-network

networks:
  django-network:
