version: "3.3"

services:
  webapp:
    build: .
    env_file:
      - base/.env.webapp.prod
    ports:
      - 8000:8000
    command: bash -c "
      cd base
      && gunicorn base.wsgi:application --bind 0.0.0.0:8000
      "
