version: "3.3"

services:
  webapp:
    build: ../django
    image: ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/django_webapp:latest
    env_file:
      - ../django/.env.webapp.prod
    expose:
      - 8000
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8000
  nginx:
    build: ../nginx
    ports:
      - 9080:80
    depends_on:
      - webapp
