# FROM nginx:1.21-alpine
FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf

# ENTRYPOINT ["tail", "-f", "/dev/null"]

# CMD ["nginx", "-g", "daemon off;"]
# CMD ["nginx", "-g", "daemon off;"]

