# Generated by Django 4.2.1 on 2023-05-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_summary_alter_post_body_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="kairos_default.jpg", upload_to="posts"),
        ),
    ]
