# Generated by Django 4.2.1 on 2023-05-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="kairos_default.jpg", upload_to=""),
        ),
    ]
