# Generated by Django 4.2.1 on 2023-05-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="conversation_file",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
