# Generated by Django 4.2.1 on 2023-05-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_conversation_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="blocks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
