# Generated by Django 4.2.1 on 2023-05-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_blocks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="blocks",
        ),
    ]
